"""Distinguish lossy displays from full-J-space linear information/conditioning."""
import argparse,json
from pathlib import Path
import numpy as np
from contracts import fingerprint
from probe_scoring import score_rows,ALGORITHM
from smoke import write_json,digest

def main():
 import torch
 p=argparse.ArgumentParser();p.add_argument('--lens',type=Path,required=True);p.add_argument('--raw-probe',type=Path,required=True);p.add_argument('--features',type=Path,required=True);p.add_argument('--out',type=Path,required=True);p.add_argument('--splits',nargs='+',choices=['train','validation','test'],default=['train','validation']);a=p.parse_args();lm=json.loads((a.lens/'manifest.json').read_text());ld=json.loads((a.lens/'complete.json').read_text());probe=json.loads(a.raw_probe.read_text());fm=json.loads((a.features/'manifest.json').read_text())
 if probe['feature_manifest_sha256']!=fingerprint(fm) or probe['endpoint'] not in {r['endpoint'] for r in fm['rows']} or probe['identity']!=lm['identity'] or fm['identity']!=lm['identity'] or digest(a.lens/'lens.pt')!=ld['lens_sha256'] or fingerprint(lm)!=ld['manifest_sha256'] or digest(a.features/'features.npz')!=fm['feature_sha256'] or fm['lens_sha256']!=ld['lens_sha256'] or probe['score_algorithm']!=ALGORITHM:raise ValueError('Provenance mismatch')
 obj=torch.load(a.lens/'lens.pt',map_location='cpu',weights_only=True);layer=probe['selected']['layer'];J=obj['J'][layer].to('cuda',torch.float64);w=torch.tensor(probe['weights'],dtype=torch.float64,device='cuda');singular=torch.linalg.svdvals(J);tolerance=J.shape[0]*torch.finfo(torch.float32).eps*singular[0];rank=int((singular>tolerance).sum());direction,solve_info=torch.linalg.solve_ex(J.T,w);solve_method='solve';
 if int(solve_info)!=0 or not torch.isfinite(direction).all():
  direction=torch.linalg.pinv(J.T,rtol=J.shape[0]*torch.finfo(torch.float64).eps)@w;solve_method='float64 pseudoinverse';
 relative_residual=float((J.T@direction-w).norm()/w.norm());arrays=np.load(a.features/'features.npz',allow_pickle=False);indices=[i for i,r in enumerate(fm['rows']) if r['layer']==layer and r['split'] in a.splits];h=torch.as_tensor(arrays['X_raw'][indices],device='cuda',dtype=torch.float64);z=torch.as_tensor(arrays['X_jspace'][indices],device='cuda',dtype=torch.float64);raw_scores=h@w+probe['intercept'];exact_scores=(h@J.T)@direction+probe['intercept'];stored_scores=z@direction+probe['intercept'];report={'splits':a.splits,'code_sha256':digest(__file__),'features_manifest_sha256':digest(a.features/'manifest.json'),'identity':lm['identity'],'layer':layer,'n_prompts':obj['n_prompts'],'raw_probe_sha256':digest(a.raw_probe),'lens_sha256':ld['lens_sha256'],'solve_method':solve_method,'solve_info':int(solve_info),'solve_relative_residual':relative_residual,'largest_singular_value':float(singular[0]),'smallest_singular_value':float(singular[-1]),'condition_number':float(singular[0]/singular[-1]) if float(singular[-1])>0 else None,'float32_scaled_tolerance_rank':rank,'rank_tolerance':float(tolerance),'dimension':len(w),'transported_direction':direction.cpu().tolist(),'intercept':probe['intercept'],'threshold':probe['threshold'],'scope':'No labels used. Reparameterize the TRAINED raw detector through the complete J matrix. Exact arithmetic equivalence does not imply numerical robustness, unsupervised interpretability, or survival in top-k token displays. FP32 rank tolerance is diagnostic, not proof of mathematical singularity.','scores':[]}
 for local,i in enumerate(indices):
  r=fm['rows'][i];report['scores'].append({'episode_id':r['episode_id'],'split':r['split'],'raw_score':float(raw_scores[local]),'float64_transport_score':float(exact_scores[local]),'stored_float32_transport_score':float(stored_scores[local])})
 report['max_float64_score_error']=float((raw_scores-exact_scores).abs().max());report['max_stored_float32_score_error']=float((raw_scores-stored_scores).abs().max());stable_raw=score_rows(arrays['X_raw'][indices],probe['weights'],probe['intercept']);stable_stored=score_rows(arrays['X_jspace'][indices],direction.cpu().numpy(),probe['intercept']);report['flag_score_algorithm']=ALGORITHM;report['stored_float32_flag_disagreements']=int(((stable_raw>=probe['threshold'])!=(stable_stored>=probe['threshold'])).sum());write_json(a.out,report)
 print(json.dumps({k:v for k,v in report.items() if k not in ['scores','transported_direction','identity','scope']}),flush=True)
if __name__=='__main__':main()
